# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Doug Davis, for your information
email: douglas.davis.092@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about technical stops along the path of getting a PhD in HEP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ddavis.fyi" # the base hostname & protocol for your site

# SEO settings
twitter:
  username: _ddavis_
author: Douglas Davis
social:
  name: Doug Davis
  links:
    - https://github.com/drdavis
    - https://twitter.com/_ddavis_

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - venv
  - vendor
sass:
  style: compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

disqus:
  shortname: ddavis-fyi
