title = "ddavis.io"
base_url = "https://ddavis.io"
compile_sass = false
build_search_index = false

generate_feeds = true
feed_filenames = ["rss.xml"]

author = "ddavis"

taxonomies = [
  { name = "tags" },
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

# [extra]
# ...
