baseURL = "https://ddavis.fyi/"
title = "Doug Davis"
theme = "manis"

# Copyright notice. Note: You can use HTML tag here
#copyright = "&copy; 2018 Douglas Davis"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
tag = "tags"

[params]
# If false, use minified CSS (ui.min.css)
debugCSS = true
# Custom CSS
customCSS = []
# Site meta description
description = "ddavis.fyi"
# Site's Tagline (Subtitle or Keyword)
tagline = "for your information"
# If true give attribution to this theme
themeAttrib = false
# URL to license file, can be outside of your domain
#licenseURL = "/about/license"

# Configure which section for Latest Posts
postSection = "blog"

# 404 Configuration
#head404 = "Sorry, I can't find what you want."
#sub404 = "Back to <a href='/'>Home</a>."

# Color of your website's accent
#colorTheme = "#ff8181"
colorTheme = "#bf5700"

# Maximum number of item in Latest Posts or Works
latestCount = 3
# Path to site's favicon image
faviconImg = ""
# Date format in item list
dateFmt = "Jan 02, 2006"

# Social Links
email = "douglas.davis.092@gmail.com"
github = "https://github.com/drdavis/"
gitlab = "https://gitlab.cern.ch/ddavis/"
twitter = "https://twitter.com/_ddavis_"
