baseurl = "https://ddavis.io/"
languageCode = "en-US"
title = "ddavis.io"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
pygmentsCodeFences = true
pygmentsUseClasses = true


[permalinks]
    post = "/post/:year/:month/:day/:slug/"

#[[menu.main]]
#    name = "Posts"
#    url = "/posts/"
#    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "rss"
    url = "/index.xml"
[params]
    description = "ddavis.io"
    footer = " "