baseurl = "http://ddavis.fyi/"
languageCode = "en-US"
title = "ddavis.fyi"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
#enableEmoji = true
footnotereturnlinkcontents = "↩"
pygmentsCodeFences = true
pygmentsStyle = "emacs"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
#[[menu.main]]
#    name = "Posts"
#    url = "/posts/"
#    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"
[params]
    description = "ddavis.fyi"
    footer = "[Mail](mailto:douglas.davis.092@gmail.com) | [GitHub](https://github.com/drdavis) | [CERN GitLab](https://gitlab.cern.ch/ddavis/) | [LinkedIn](https://www.linkedin.com/in/douglasrdavis/) | [Twitter](https://twitter.com/_ddavis_)"
    custom_css = ["css/theme-override.css"]
